### ISSUE TITLE
question on license

### ISSUE THREAD

**Issue by weakcamel** [swift-nav/cmake#90]
I stumbled across this repository while looking for some cmake modules and found it quite interesting.

The repository doesn't specify the license of this code though which is quite essential in my opinion. Would it be possible to clarify what it is?

Thanks  in advance!

**Comment by woodfell** [comment]
Hi @weakcamel , thanks for the message. The modules in this repository are to support various public and internal build systems and processes but I'm glad you found them interesting.

To answer your question everything is under an MIT license. You're right, there should be a license notice attached to everything in here, I'll see it gets added.

**Comment by weakcamel** [comment]
Great, thank you @woodfell !
